from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/analytics/', views.dashboard_analytics, name='dashboard_analytics'),
    path('documents/', views.document_list, name='document_list'),
    path('documents/export/', views.document_export, name='document_export'),
    path('documents/tags/autocomplete/', views.tag_autocomplete, name='tag_autocomplete'),
    path('documents/create/', views.document_create, name='document_create'),
    path('documents/<str:slug>/preview/', views.document_pdf_preview, name='document_pdf_preview'),
    path('documents/<str:slug>/comments/', views.document_comment_create, name='document_comment_create'),
    path('documents/<str:slug>/comments/<int:comment_id>/delete/', views.document_comment_delete, name='document_comment_delete'),
    path('documents/<str:slug>/links/search/', views.document_link_search, name='document_link_search'),
    path('documents/<str:slug>/links/', views.document_link_create, name='document_link_create'),
    path('documents/<str:slug>/links/<int:link_id>/delete/', views.document_link_delete, name='document_link_delete'),
    path('documents/<str:slug>/', views.document_detail, name='document_detail'),
    path('documents/<str:slug>/edit/', views.document_edit, name='document_edit'),
    path('documents/<str:slug>/delete/', views.document_delete, name='document_delete'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/create/', views.category_create, name='category_create'),
    path('categories/<int:pk>/edit/', views.category_edit, name='category_edit'),
    path('categories/<int:pk>/delete/', views.category_delete, name='category_delete'),
    path('audit/', views.audit_log_list, name='audit_log'),
    path('settings/notifications/', views.notification_settings, name='notification_settings'),
    path('settings/users/', views.user_list, name='user_list'),
    path('settings/users/invite/', views.user_invite, name='user_invite'),
    path('settings/users/<int:user_id>/role/', views.user_update_role, name='user_update_role'),
    path('settings/users/<int:user_id>/block/', views.user_block, name='user_block'),
    path('settings/users/<int:user_id>/delete/', views.user_delete, name='user_delete'),
    path('invite/<uidb64>/<token>/', views.invite_set_password, name='invite_set_password'),
    path('login/', auth_views.LoginView.as_view(template_name='documents/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
]
