[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate --noinput && gunicorn config.wsgi --log-file -"
