# Generated by Django 6.0.6 on 2026-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_pdf_file_alter_document_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pages',
        ),
        migrations.AddField(
            model_name='document',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма договора'),
        ),
        migrations.AddField(
            model_name='document',
            name='initiator',
            field=models.CharField(blank=True, max_length=255, verbose_name='Инициатор'),
        ),
    ]
