# Generated by Django 4.2 on 2026-06-15 09:33

import re

from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify
import django.db.models.deletion


def migrate_tags_and_slugs(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    Tag = apps.get_model('documents', 'Tag')

    for document in Document.objects.all():
        raw_tags = getattr(document, 'tags_legacy', '') or ''
        if raw_tags:
            names = [t.strip() for t in re.split(r'[,;\s]+', raw_tags) if t.strip()]
            tag_objects = []
            for name in names:
                tag, _ = Tag.objects.get_or_create(name=name)
                tag_objects.append(tag)
            document.tags.set(tag_objects)

        if not document.slug:
            base_slug = slugify(document.title, allow_unicode=True) or f'document-{document.pk}'
            slug = base_slug
            counter = 2
            while Document.objects.filter(slug=slug).exclude(pk=document.pk).exists():
                slug = f'{base_slug}-{counter}'
                counter += 1
            document.slug = slug
            document.save(update_fields=['slug'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_document_slug_alter_category_id_alter_document_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_text',
            field=models.TextField(blank=True, editable=False, verbose_name='Текст PDF'),
        ),
        migrations.AddField(
            model_name='document',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RenameField(
            model_name='document',
            old_name='tags',
            new_name='tags_legacy',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Просмотр'), ('editor', 'Редактор'), ('admin', 'Администратор')], default='editor', max_length=10, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/versions/', verbose_name='PDF файл')),
                ('version_number', models.PositiveIntegerField(verbose_name='Версия')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Документ')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Версия документа',
                'verbose_name_plural': 'Версии документов',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=10, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=50, verbose_name='Модель')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Объект')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.tag', verbose_name='Теги'),
        ),
        migrations.RunPython(migrate_tags_and_slugs, noop),
        migrations.RemoveField(
            model_name='document',
            name='tags_legacy',
        ),
    ]
