# Generated by Django 4.2 on 2026-06-16 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0005_tag_document_end_date_document_pdf_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_email_enabled', models.BooleanField(default=True, verbose_name='Email-уведомления')),
                ('notify_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notify_telegram_enabled', models.BooleanField(default=False, verbose_name='Telegram-уведомления')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=128, verbose_name='Telegram Chat ID')),
                ('notify_30_days', models.BooleanField(default=True, verbose_name='За 30 дней')),
                ('notify_7_days', models.BooleanField(default=True, verbose_name='За 7 дней')),
                ('notify_on_expiry_day', models.BooleanField(default=False, verbose_name='В день истечения')),
                ('dashboard_expiry_days', models.PositiveIntegerField(default=30, verbose_name='Порог виджета (дней)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
