# Generated by Django 4.2 on 2026-06-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_user_notification_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='initiator',
            new_name='signatory',
        ),
    ]
