# Generated by Django 4.2 on 2026-06-16 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_comments_and_version_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('supplement', 'Дополнительное соглашение'), ('act', 'Акт выполненных работ'), ('invoice', 'Счёт'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип связи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='documents.document', verbose_name='Документ')),
                ('linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='documents.document', verbose_name='Связанный документ')),
            ],
            options={
                'verbose_name': 'Связь документов',
                'verbose_name_plural': 'Связи документов',
                'db_table': 'document_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentlink',
            constraint=models.UniqueConstraint(fields=('document', 'linked'), name='unique_document_link'),
        ),
    ]
