# Generated by Django 4.2 on 2026-06-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
    ]
