# Generated by Django 4.2 on 2026-06-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='with_vat',
            field=models.BooleanField(default=False, verbose_name='С НДС'),
        ),
    ]
