# Generated by Django 4.2 on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_with_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Компания'),
        ),
    ]
