# Generated by Django 4.2 on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_document_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='company_type',
            field=models.CharField(
                blank=True,
                choices=[('too', 'ТОО'), ('ip', 'ИП'), ('ao', 'АО')],
                max_length=10,
                verbose_name='Тип компании',
            ),
        ),
    ]
