EXTRA_TRANSLATIONS = {
    "+ Добавить документ": {"en": "+ Add document", "kk": "+ Құжат қосу"},
    "12 мес": {"en": "12 mo", "kk": "12 ай"},
    "3 мес": {"en": "3 mo", "kk": "3 ай"},
    "6 мес": {"en": "6 mo", "kk": "6 ай"},
    "API — PDF Data Base": {"en": "API — PDF Data Base", "kk": "API — PDF Data Base"},
    "API-ключ": {"en": "API key", "kk": "API кілті"},
    "API-ключ создан. Скопируйте его сейчас — больше он не будет показан.": {"en": "API key created. Copy it now — it will not be shown again.", "kk": "API кілті жасалды. Қазір көшіріңіз — қайта көрсетілмейді."},
    "API-ключ удалён.": {"en": "API key deleted.", "kk": "API кілті жойылды."},
    "API-ключей пока нет": {"en": "No API keys yet", "kk": "API кілттері әлі жоқ"},
    "API-ключи": {"en": "API keys", "kk": "API кілттері"},
    "Email": {"en": "Email", "kk": "Email"},
    "Email-уведомления": {"en": "Email notifications", "kk": "Email хабарландырулары"},
    "Enter или запятая добавляет тег": {"en": "Enter or comma adds a tag", "kk": "Enter немесе үтір тег қосады"},
    "ID объекта": {"en": "Object ID", "kk": "Объект ID"},
    "PDF Data Base — Система управления документами": {"en": "PDF Data Base — Document management system", "kk": "PDF Data Base — Құжаттарды басқару жүйесі"},
    "PDF файл не загружен": {"en": "PDF file not uploaded", "kk": "PDF файлы жүктелмеген"},
    "Telegram Chat ID": {"en": "Telegram Chat ID", "kk": "Telegram Chat ID"},
    "Telegram-уведомления": {"en": "Telegram notifications", "kk": "Telegram хабарландырулары"},
    "А → Я": {"en": "A → Z", "kk": "A → Z"},
    "Акт": {"en": "Act", "kk": "Акт"},
    "Акт выполненных работ": {"en": "Work completion certificate", "kk": "Орындалған жұмыстар актісі"},
    "Быстрый поиск": {"en": "Quick search", "kk": "Жылдам іздеу"},
    "В день истечения": {"en": "On expiry day", "kk": "Мерзімі біткен күні"},
    "Введите запрос для поиска": {"en": "Enter a search query", "kk": "Іздеу сұрауын енгізіңіз"},
    "Введите логин": {"en": "Enter username", "kk": "Логинді енгізіңіз"},
    "Введите пароль": {"en": "Enter password", "kk": "Құпия сөзді енгізіңіз"},
    "Введите тег и нажмите Enter": {"en": "Enter a tag and press Enter", "kk": "Тег енгізіп Enter басыңыз"},
    "Введите текст комментария.": {"en": "Enter comment text.", "kk": "Пікір мәтінін енгізіңіз."},
    "Версии документов": {"en": "Document versions", "kk": "Құжат нұсқалары"},
    "Версий пока нет": {"en": "No versions yet", "kk": "Нұсқалар әлі жоқ"},
    "Версия": {"en": "Version", "kk": "Нұсқа"},
    "Версия документа": {"en": "Document version", "kk": "Құжат нұсқасы"},
    "Возможности": {"en": "Features", "kk": "Мүмкіндіктер"},
    "Время": {"en": "Time", "kk": "Уақыт"},
    "Все договоры": {"en": "All contracts", "kk": "Барлық келісімдер"},
    "Все документы": {"en": "All documents", "kk": "Барлық құжаттар"},
    "Вход — PDF Data Base": {"en": "Sign in — PDF Data Base", "kk": "Кіру — PDF Data Base"},
    "Вы уверены, что хотите удалить <strong>{{ name }}</strong>?": {"en": "Are you sure you want to delete <strong>{{ name }}</strong>?", "kk": "<strong>{{ name }}</strong> жойғыңыз келетініне сенімдісіз бе?"},
    "Вы уверены, что хотите удалить <strong>{{ title }}</strong>? Это действие нельзя отменить.": {"en": "Are you sure you want to delete <strong>{{ title }}</strong>? This action cannot be undone.", "kk": "<strong>{{ title }}</strong> жойғыңыз келетініне сенімдісіз бе? Бұл әрекетті болдырмау мүмкін емес."},
    "Выберите документ для связи.": {"en": "Select a document to link.", "kk": "Байланыс үшін құжат таңдаңыз."},
    "Выбрано: {{ count }}": {"en": "Selected: {{ count }}", "kk": "Таңдалды: {{ count }}"},
    "Группировка документов": {"en": "Document grouping", "kk": "Құжаттарды топтау"},
    "Дата добавления": {"en": "Date added", "kk": "Қосылған күні"},
    "Дата истечения": {"en": "Expiry date", "kk": "Мерзімі"},
    "Дата обновления": {"en": "Updated at", "kk": "Жаңартылған күні"},
    "Дата окончания не может быть раньше даты начала.": {"en": "End date cannot be before start date.", "kk": "Аяқталу күні басталу күнінен ерте болмауы керек."},
    "Дата создания": {"en": "Created at", "kk": "Жасалған күні"},
    "Дашборд — PDF Data Base": {"en": "Dashboard — PDF Data Base", "kk": "Басты бет — PDF Data Base"},
    "Действие": {"en": "Action", "kk": "Әрекет"},
    "Действия": {"en": "Actions", "kk": "Әрекеттер"},
    "Да": {"en": "Yes", "kk": "Иә"},
    "Детали": {"en": "Details", "kk": "Толығырақ"},
    "Добавить связанный документ": {"en": "Add linked document", "kk": "Байланысты құжат қосу"},
    "Добавить связь": {"en": "Add link", "kk": "Байланыс қосу"},
    "Добавлен": {"en": "Added", "kk": "Қосылды"},
    "Договор истекает {{ date }}": {"en": "Contract expires {{ date }}", "kk": "Келісім мерзімі {{ date }}"},
    "Договор просрочен (окончание: {{ date }})": {"en": "Contract expired (end: {{ date }})", "kk": "Келісім мерзімі өткен (аяқталу: {{ date }})"},
    "Документация:": {"en": "Documentation:", "kk": "Құжаттама:"},
    "Документы не найдены.": {"en": "No documents found.", "kk": "Құжаттар табылмады."},
    "Документы — PDF Data Base": {"en": "Documents — PDF Data Base", "kk": "Құжаттар — PDF Data Base"},
    "Доп. согл.": {"en": "Suppl.", "kk": "Қос. кел."},
    "Дополнительное соглашение": {"en": "Supplementary agreement", "kk": "Қосымша келісім"},
    "Доступ запрещён — PDF Data Base": {"en": "Access denied — PDF Data Base", "kk": "Қол жеткізу тыйым — PDF Data Base"},
    "Другое": {"en": "Other", "kk": "Басқа"},
    "Журнал изменений — PDF Data Base": {"en": "Audit log — PDF Data Base", "kk": "Өзгерістер журналы — PDF Data Base"},
    "За 30 дней": {"en": "30 days before", "kk": "30 күн бұрын"},
    "За 30 дней до истечения договора": {"en": "30 days before contract expiry", "kk": "Келісім мерзімі біткенге 30 күн бұрын"},
    "За 7 дней": {"en": "7 days before", "kk": "7 күн бұрын"},
    "За 7 дней до истечения договора": {"en": "7 days before contract expiry", "kk": "Келісім мерзімі біткенге 7 күн бұрын"},
    "Заблокировать": {"en": "Block", "kk": "Блоктау"},
    "Заблокировать пользователя {{ username }}?": {"en": "Block user {{ username }}?", "kk": "{{ username }} пайдаланушысын блоктау керек пе?"},
    "Загружено": {"en": "Uploaded", "kk": "Жүктелді"},
    "Загрузите PDF файл — он сохранится в облаке": {"en": "Upload a PDF — it will be stored in the cloud", "kk": "PDF жүктеңіз — ол бұлтта сақталады"},
    "Загрузить новый PDF-договор": {"en": "Upload new PDF contract", "kk": "Жаңа PDF келісім жүктеу"},
    "Загрузка PDF…": {"en": "Loading PDF…", "kk": "PDF жүктелуде…"},
    "Закрыть": {"en": "Close", "kk": "Жабу"},
    "Замена PDF файла": {"en": "Replace PDF file", "kk": "PDF файлын ауыстыру"},
    "Заменить (старая версия сохранится)": {"en": "Replace (previous version will be saved)", "kk": "Ауыстыру (ескі нұсқа сақталады)"},
    "Записей пока нет": {"en": "No records yet", "kk": "Жазбалар әлі жоқ"},
    "Имя": {"en": "Name", "kk": "Аты"},
    "Используйте заголовок: <code>Authorization: Bearer {{ key }}</code>": {"en": "Use header: <code>Authorization: Bearer {{ key }}</code>", "kk": "Тақырыпты қолданыңыз: <code>Authorization: Bearer {{ key }}</code>"},
    "Истекает в {{ days }} дней": {"en": "Expiring in {{ days }} days", "kk": "{{ days }} күнде мерзімі бітеді"},
    "Истекают в ближайшие {{ days }} дней:": {"en": "Expiring in the next {{ days }} days:", "kk": "Жақын {{ days }} күнде мерзімі бітеді:"},
    "История изменений": {"en": "Change history", "kk": "Өзгерістер тарихы"},
    "Категории — PDF Data Base": {"en": "Categories — PDF Data Base", "kk": "Санаттар — PDF Data Base"},
    "Категория обновлена!": {"en": "Category updated!", "kk": "Санат жаңартылды!"},
    "Категория создана!": {"en": "Category created!", "kk": "Санат жасалды!"},
    "Категория удалена!": {"en": "Category deleted!", "kk": "Санат жойылды!"},
    "Ключ": {"en": "Key", "kk": "Кілт"},
    "Когда уведомлять:": {"en": "When to notify:", "kk": "Қашан хабарлау:"},
    "Комментариев пока нет": {"en": "No comments yet", "kk": "Пікірлер әлі жоқ"},
    "Комментарий": {"en": "Comment", "kk": "Пікір"},
    "Комментарий слишком длинный.": {"en": "Comment is too long.", "kk": "Пікір тым ұзын."},
    "Контрагент": {"en": "Counterparty", "kk": "Контрагент"},
    "Копировать": {"en": "Copy", "kk": "Көшіру"},
    "Максимум 365 дней.": {"en": "Maximum 365 days.", "kk": "Максимум 365 күн."},
    "Модель": {"en": "Model", "kk": "Модель"},
    "На страницу входа": {"en": "Go to sign in", "kk": "Кіру бетіне"},
    "На указанный email будет отправлена ссылка для установки пароля.": {"en": "A password setup link will be sent to the email provided.", "kk": "Көрсетілген email-ге құпия сөз орнату ссылкасы жіберіледі."},
    "Название *": {"en": "Title *", "kk": "Атауы *"},
    "Название документа": {"en": "Document title", "kk": "Құжат атауы"},
    "Название, контрагент...": {"en": "Title, counterparty...", "kk": "Атау, контрагент..."},
    "Написать комментарий...": {"en": "Write a comment...", "kk": "Пікір жазу..."},
    "Например: Интеграция 1С": {"en": "e.g. 1C integration", "kk": "мысалы: 1С интеграциясы"},
    "Настройки уведомлений": {"en": "Notification settings", "kk": "Хабарландыру баптаулары"},
    "Настройки уведомлений сохранены.": {"en": "Notification settings saved.", "kk": "Хабарландыру баптаулары сақталды."},
    "Неверный логин или пароль": {"en": "Invalid username or password", "kk": "Логин немесе құпия сөз дұрыс емес"},
    "Нет": {"en": "No", "kk": "Жоқ"},
    "Нет описания": {"en": "No description", "kk": "Сипаттама жоқ"},
    "Нет пользователей": {"en": "No users", "kk": "Пайдаланушылар жоқ"},
    "Новая категория": {"en": "New category", "kk": "Жаңа санат"},
    "Новый пароль": {"en": "New password", "kk": "Жаңа құпия сөз"},
    "Обновлён": {"en": "Updated", "kk": "Жаңартылды"},
    "Объект": {"en": "Object", "kk": "Объект"},
    "Окончание": {"en": "End", "kk": "Аяқталу"},
    "Открыть PDF": {"en": "Open PDF", "kk": "PDF ашу"},
    "Открыть дашборд": {"en": "Open dashboard", "kk": "Басты бетті ашу"},
    "Отправить приглашение": {"en": "Send invitation", "kk": "Шақыру жіберу"},
    "Очистить поиск": {"en": "Clear search", "kk": "Іздеуді тазалау"},
    "Пароли не совпадают.": {"en": "Passwords do not match.", "kk": "Құпия сөздер сәйкес келмейді."},
    "Пароль должен содержать минимум 8 символов.": {"en": "Password must be at least 8 characters.", "kk": "Құпия сөз кемінде 8 таңбадан тұруы керек."},
    "Пароль установлен. Теперь можно войти.": {"en": "Password set. You can sign in now.", "kk": "Құпия сөз орнатылды. Енді кіруге болады."},
    "Период графика": {"en": "Chart period", "kk": "График кезеңі"},
    "Повторите пароль": {"en": "Repeat password", "kk": "Құпия сөзді қайталаңыз"},
    "Поиск по названию, категории, подписанту...": {"en": "Search by title, category, signatory...", "kk": "Атау, санат, қол қоюшы бойынша іздеу..."},
    "Показывать документы, которые истекают через": {"en": "Show documents expiring within", "kk": "Мерзімі бітетін құжаттарды көрсету"},
    "Пользователи — PDF Data Base": {"en": "Users — PDF Data Base", "kk": "Пайдаланушылар — PDF Data Base"},
    "Пользователь": {"en": "User", "kk": "Пайдаланушы"},
    "Пользователь %(username)s заблокирован.": {"en": "User %(username)s blocked.", "kk": "Пайдаланушы %(username)s блокталды."},
    "Пользователь %(username)s удалён.": {"en": "User %(username)s deleted.", "kk": "Пайдаланушы %(username)s жойылды."},
    "Пользователь с таким email уже существует.": {"en": "A user with this email already exists.", "kk": "Мұндай email бар пайдаланушы бар."},
    "Пользователь создан, но письмо не отправлено. Ссылка: %(url)s": {"en": "User created but email not sent. Link: %(url)s", "kk": "Пайдаланушы жасалды, бірақ хат жіберілмеді. Ссылка: %(url)s"},
    "Порог виджета (дней)": {"en": "Widget threshold (days)", "kk": "Виджет порогы (күн)"},
    "Порог виджета на дашборде": {"en": "Dashboard widget threshold", "kk": "Басты бет виджет порогы"},
    "Последнее использование": {"en": "Last used", "kk": "Соңғы қолдану"},
    "Последний вход": {"en": "Last login", "kk": "Соңғы кіру"},
    "Пригласить пользователя": {"en": "Invite user", "kk": "Пайдаланушы шақыру"},
    "Приглашение отправлено на %(email)s.": {"en": "Invitation sent to %(email)s.", "kk": "Шақыру %(email)s адресіне жіберілді."},
    "Проверьте email и роль.": {"en": "Check email and role.", "kk": "Email мен рөлді тексеріңіз."},
    "Просмотр и поиск по базе": {"en": "Browse and search the database", "kk": "Базадан қарау және іздеу"},
    "Профили пользователей": {"en": "User profiles", "kk": "Пайдаланушы профильдері"},
    "Профиль пользователя": {"en": "User profile", "kk": "Пайдаланушы профилі"},
    "Размер файла": {"en": "File size", "kk": "Файл өлшемі"},
    "Размер файла не должен превышать %(max)s МБ": {"en": "File size must not exceed %(max)s MB", "kk": "Файл өлшемі %(max)s МБ-дан аспауы керек"},
    "Редактировать категорию": {"en": "Edit category", "kk": "Санатты өңдеу"},
    "Результаты поиска": {"en": "Search results", "kk": "Іздеу нәтижелері"},
    "Роль": {"en": "Role", "kk": "Рөл"},
    "Роль пользователя %(username)s обновлена.": {"en": "Role for user %(username)s updated.", "kk": "Пайдаланушы %(username)s рөлі жаңартылды."},
    "Связанный документ": {"en": "Linked document", "kk": "Байланысты құжат"},
    "Связи документов": {"en": "Document links", "kk": "Құжат байланыстары"},
    "Связь документов": {"en": "Document link", "kk": "Құжат байланысы"},
    "Система управления вашими документами": {"en": "Your document management system", "kk": "Құжаттарды басқару жүйесіңіз"},
    "Создал": {"en": "Created by", "kk": "Жасаған"},
    "Создано": {"en": "Created", "kk": "Жасалған"},
    "Создать API-ключ": {"en": "Create API key", "kk": "API кілті жасау"},
    "Создать первую": {"en": "Create first", "kk": "Бirinшisін жасау"},
    "Сохраните ключ — он больше не будет показан": {"en": "Save the key — it will not be shown again", "kk": "Кілтті сақтаңыз — қайта көрсетілмейді"},
    "Сохранить и войти": {"en": "Save and sign in", "kk": "Сақтап кіру"},
    "Срок действия приглашения истёк или ссылка уже использована. Обратитесь к администратору.": {"en": "Invitation expired or link already used. Contact your administrator.", "kk": "Шақыру мерзімі өтті немесе ссылка қолданылған. Әкімшіге хабарласыңыз."},
    "Ссылка недействительна": {"en": "Invalid link", "kk": "Ссылка жарамсыз"},
    "Ссылка недействительна — PDF Data Base": {"en": "Invalid link — PDF Data Base", "kk": "Ссылка жарамсыз — PDF Data Base"},
    "Статистика": {"en": "Statistics", "kk": "Статистика"},
    "Стр. {{ page }} из {{ total }}": {"en": "Page {{ page }} of {{ total }}", "kk": "Бет {{ page }} / {{ total }}"},
    "Сумма (₸)": {"en": "Amount (₸)", "kk": "Сома (₸)"},
    "Сумма договора (₸)": {"en": "Contract amount (₸)", "kk": "Келісім сомасы (₸)"},
    "С НДС": {"en": "With VAT", "kk": "ҚҚС-пен"},
    "Суммы, сроки": {"en": "Amounts and deadlines", "kk": "Сомалар, мерзімдер"},
    "Суффикс": {"en": "Suffix", "kk": "Сuffix"},
    "Счёт": {"en": "Invoice", "kk": "Шот"},
    "Тег": {"en": "Tag", "kk": "Тег"},
    "Текст": {"en": "Text", "kk": "Мәтін"},
    "Текст PDF": {"en": "PDF text", "kk": "PDF мәтіні"},
    "Тип связи": {"en": "Link type", "kk": "Байланыс түрі"},
    "У вас недостаточно прав для просмотра этой страницы.": {"en": "You do not have permission to view this page.", "kk": "Бұл бетті көруге құқығыңыз жеткіліксіз."},
    "Убрать фильтр": {"en": "Remove filter", "kk": "Сүзгіні алу"},
    "Уведомления о сроках договоров": {"en": "Contract expiry notifications", "kk": "Келісім мерзімі хабарландырулары"},
    "Уведомления — PDF Data Base": {"en": "Notifications — PDF Data Base", "kk": "Хабарландырулар — PDF Data Base"},
    "Уведомлять меня по:": {"en": "Notify me via:", "kk": "Мені хабарлау:"},
    "Удалить API-ключ «{{ name }}»?": {"en": "Delete API key «{{ name }}»?", "kk": "API кілті «{{ name }}» жойылсын ба?"},
    "Удалить документ — PDF Data Base": {"en": "Delete document — PDF Data Base", "kk": "Құжатты жою — PDF Data Base"},
    "Удалить документ?": {"en": "Delete document?", "kk": "Құжатты жою керек пе?"},
    "Удалить категорию — PDF Data Base": {"en": "Delete category — PDF Data Base", "kk": "Санатты жою — PDF Data Base"},
    "Удалить категорию?": {"en": "Delete category?", "kk": "Санатты жою керек пе?"},
    "Удалить пользователя {{ username }}? Это действие необратимо.": {"en": "Delete user {{ username }}? This action is irreversible.", "kk": "{{ username }} пайдаланушысын жою керек пе? Бұл әрекетті к geri алу мүмкін емес."},
    "Укажите Telegram Chat ID или ссылку.": {"en": "Provide Telegram Chat ID or link.", "kk": "Telegram Chat ID немесе ссылка көрсетіңіз."},
    "Укажите email для уведомлений.": {"en": "Provide email for notifications.", "kk": "Хабарландырулар үшін email көрсетіңіз."},
    "Укажите значение от 1 до 365.": {"en": "Enter a value from 1 to 365.", "kk": "1-ден 365-ке дейін мән көрсетіңіз."},
    "Укажите название ключа.": {"en": "Provide key name.", "kk": "Кілт атауын көрсетіңіз."},
    "Управление API-ключами": {"en": "API key management", "kk": "API кілттерін басқару"},
    "Управление категориями": {"en": "Category management", "kk": "Санаттарды басқaru"},
    "Управление пользователями": {"en": "User management", "kk": "Пайдаланушыларды басқaru"},
    "Установка пароля": {"en": "Set password", "kk": "Құпия сөз орнату"},
    "Установка пароля — PDF Data Base": {"en": "Set password — PDF Data Base", "kk": "Құпия сөз орнату — PDF Data Base"},
    "Имя": {"en": "Name", "kk": "Аты"},
    "Введите имя": {"en": "Enter name", "kk": "Атын енгізіңіз"},
    "Укажите имя.": {"en": "Please enter a name.", "kk": "Атын көрсетіңіз."},
    "Имя пользователя обновлено: %(name)s.": {
        "en": "User name updated: %(name)s.",
        "kk": "Пайдаланушы аты жаңартылды: %(name)s.",
    },
    "Проверьте имя, email и роль.": {
        "en": "Check name, email, and role.",
        "kk": "Аты, email және рөлді тексеріңіз.",
    },
    "ФИО автора": {"en": "Author full name", "kk": "Автордың ТАӘ"},
    "ФИО подписанта": {"en": "Signatory full name", "kk": "Қол қоюшының ТАӘ"},
    "Файл должен быть в формате PDF": {"en": "File must be in PDF format", "kk": "Файл PDF форматында болуы керек"},
    "Хеш ключа": {"en": "Key hash", "kk": "Кілт хеші"},
    "Числовой Chat ID (через @userinfobot) или ссылка на профиль": {"en": "Numeric Chat ID (via @userinfobot) or profile link", "kk": "Сандық Chat ID (@userinfobot) немесе профиль ссылkasy"},
    "Что сделать с новым файлом?": {"en": "What to do with the new file?", "kk": "Жаңа файлмен не істеу керек?"},
    "Этот документ уже содержит файл.": {"en": "This document already has a file.", "kk": "Бұл құжатта файл бар."},
    "в одном месте": {"en": "in one place", "kk": "бір жерде"},
    "вы": {"en": "yes", "kk": "иә"},
    "дней": {"en": "days", "kk": "күн"},
    "до %(date)s": {"en": "until %(date)s", "kk": "%(date)s дейін"},
    "заблокирован": {"en": "blocked", "kk": "блокталған"},
    "загрузить": {"en": "upload", "kk": "жүктеу"},
    "и статистика": {"en": "and statistics", "kk": "және статистика"},
    "от %(date)s": {"en": "from %(date)s", "kk": "%(date)s бастап"},
    "по любым полям": {"en": "across all fields", "kk": "барлық өрістер бойынша"},
    "сумма до %(amount)s ₸": {"en": "amount up to %(amount)s ₸", "kk": "сома %(amount)s ₸ дейін"},
    "сумма от %(amount)s ₸": {"en": "amount from %(amount)s ₸", "kk": "сома %(amount)s ₸ бастап"},
}
